### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by ilensb** [iw4p/proxy-scraper#27]
https://github.com/iw4p/proxy-scraper/blob/452c6107927a8ccf7d4590292952733d7bb3aa80/proxyScraper.py#L81

**Comment by iw4p** [comment]
Hello,
May I know what you command did you use? I checked, and the script works fine.
You'll get this error when the result of the previous variable is None, so `findAll` won't work on None value.

**Comment by ilensb** [comment]
![Screenshot 2023-01-02 at 03 42 24](https://user-images.githubusercontent.com/25704996/210190130-1a8c350f-ffcd-40a5-af70-a96a431d55cb.png)

**Comment by iw4p** [comment]
Check and install the newest version of beautifulsoup4 library. And also you can use the old commits and see if they are working or not, because it works fine.
<img width="552" alt="proxy-scraper" src="https://user-images.githubusercontent.com/30632761/210259290-0a26da58-bd87-45a2-85e8-bbae2d4242d5.png">

**Comment by ilensb** [comment]
Yes works fine now. Thanks.
